using DevPurge.Core.Models;

namespace DevPurge.Core.Purging;

/// <summary>
/// Status of an item evaluated during dry-run verification.
/// </summary>
public enum DryRunStatus
{
    Eligible,
    Unsafe,
    LockedOrInaccessible,
    NotFound
}

/// <summary>
/// Result of evaluating a single discovered folder in dry-run mode.
/// </summary>
public record DryRunItem(
    string Path,
    string FolderName,
    string CategoryName,
    long SizeBytes,
    string FormattedSize,
    DryRunStatus Status,
    string? Reason
);

/// <summary>
/// Comprehensive evaluation report generated by dry-run verification.
/// </summary>
public record DryRunReport(
    int TotalEvaluated,
    int EligibleCount,
    int UnsafeCount,
    int LockedCount,
    long EligibleBytes,
    IReadOnlyList<DryRunItem> Items
)
{
    public string FormattedEligibleSize => DiscoveredFolder.FormatByteSize(EligibleBytes);
    public bool AllEligible => TotalEvaluated > 0 && EligibleCount == TotalEvaluated;
}
